Update add_new_block.yml

diff --git a/.github/workflows/add_new_block.yml b/.github/workflows/add_new_block.yml
--- a/.github/workflows/add_new_block.yml
+++ b/.github/workflows/add_new_block.yml
@@ -33,11 +33,26 @@ jobs:
 
     - name: Add Template Text to database.js
       run: |
-        # Parse the current database.js content
-        databaseContent=$(cat database.js)
+        # Parse the current database.js content using jq (if it's valid JSON)
+        if jq . database.js > /dev/null 2>&1; then
+          # Append the template content to the .pages.page1.blocks array
+          jq --argjson newBlock "$(<template.js)" '.pages.page1.blocks += [$newBlock]' database.js > updated_database.js
 
-        # Append the template content to the .pages.page1.blocks array
-        updatedDatabaseContent=$(echo "$databaseContent" | jq --argjson newBlock "$templateContent" '.pages.page1.blocks += [$newBlock]')
+          # Save the updated content back to the database.js file
+          mv updated_database.js database.js
+        else
+          echo "Error: The current database.js content is not in valid JSON format."
+          exit 1
+        fi
 
-        # Save the updated content back to the database.js file
-        echo "$updatedDatabaseContent" > database.js
+    - name: Commit and Push Changes
+      uses: stefanzweifel/git-auto-commit-action@v4
+      with:
+        commit_message: "Add new block: ${{ github.event.client_payload.blockName }}"
+        commit_user_name: "timmit147"
+        commit_user_email: "timmeeuwsen@hotmail.nl"
+        commit_author: "timmit147 <timmeeuwsen@hotmail.nl>"
+        commit: true
+        push: true
+      env:
+        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
